name: Deploy app to production (render app)

on:
  push:
    branches:
      - main

jobs:
    publish-docker-hub:
        name: Publish Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Build Docker image for frontend
                uses: docker/build-push-action@v6
                with:
                    context: ./curistore-frontend
                    push: true
                    tags: ${{ secrets.DOCKER_USERNAME }}/curistore-frontend:latest
            -   name: Build Docker image for backend
                uses: docker/build-push-action@v6
                with:
                    context: ./curistore-backend
                    push: true
                    tags: ${{ secrets.DOCKER_USERNAME }}/curistore-backend:latest